apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: mvs
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: device-backend-api
  